 version: "3.3"

 services:
   api-users:
     build: ./api-perfil-2
     image: leonelcd/api-perfil-2
     ports:
       - 8001:8001
   api-images:
     build: ./api-imagn
     image: leonelcd/api-imagn
     ports:
       - 8002:8002
   api-interaction:
     build: ./api-interacciones
     image: leonelcd/api-interacciones
     ports:
       - 8003:8003
